# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#   
#   cities = City.create([{ ::name => 'Chicago' }, { ::name => 'Copenhagen' }])
#   Major.create(::name => 'Daley', :city => cities.first)
League.create :name => "English Premium", :url_param => "EngPrem"
League.create :name => "English Championship", :url_param => "EngChamp"
League.create :name => "English 1st Division", :url_param => "EngDiv1"
League.create :name => "English 2nd Division", :url_param => "EngDiv2"
League.create :name => "English Conference", :url_param => "EngConf"
League.create :name => "Scotland Premium", :url_param => "ScotPrem"
League.create :name => "Scotland 1st Division", :url_param => "ScotDiv1"
League.create :name => "Scotland 2nd Division", :url_param => "ScotDiv2"
League.create :name => "Scotland 3rd Division", :url_param => "ScotDiv3"
League.create :name => "Italy Serie A", :url_param => "Italy_A"
League.create :name => "Italy Serie B ", :url_param => "Italy_B"
League.create :name => "Italy C1A ", :url_param => "Italy_C1A"
League.create :name => "Italy C1B ", :url_param => "Italy_C1B"
League.create :name => "Germany Bundesliga", :url_param => "Bundesliga"
League.create :name => "Germany Second Bundesliga", :url_param => "2.Bundes"
League.create :name => "Germany Regional South", :url_param => "GerRegS"
League.create :name => "Germany Regional North", :url_param => "GerRegN"
League.create :name => "France D1", :url_param => "FranceD1"
League.create :name => "France D2", :url_param => "FranceD2"
League.create :name => "Spain", :url_param => "PrimeraDiv"
League.create :name => "Spain 2nd", :url_param => "SegundaDiv"
League.create :name => "Portugal", :url_param => "Portugal"
League.create :name => "Holland", :url_param => "Holland"
League.create :name => "Holland 1st Division", :url_param => "HollErste"
League.create :name => "Belgian", :url_param => "Belgian"
League.create :name => "Austria", :url_param => "Austria"
League.create :name => "Austria 1st Division", :url_param => "AutErste"
League.create :name => "Croatia", :url_param => "Croatia"
League.create :name => "Czech R.", :url_param => "CzechR."
League.create :name => "Denmark", :url_param => "Denmark"
League.create :name => "Denmark 1st Division", :url_param => "DenDiv1"
League.create :name => "Finland", :url_param => "Finland"
League.create :name => "Finland 1st Division", :url_param => "FinDiv1"
League.create :name => "Finland Cup", :url_param => "FinlandLC"
League.create :name => "Greece", :url_param => "Greece"
League.create :name => "Ireland Premium", :url_param => "IRLPrem"
League.create :name => "Ireland 1st Division", :url_param => "IRLDiv1"
League.create :name => "Ireland FAI Cup", :url_param => "FAI_Cup"
League.create :name => "Ireland League Cup", :url_param => "IrelandLC"
League.create :name => "Norway", :url_param => "Norway"
League.create :name => "Norway Division 1", :url_param => "NorDiv1"
League.create :name => "Norway Cup", :url_param => "NorwayCup"
League.create :name => "Poland", :url_param => "Poland"
League.create :name => "Russia", :url_param => "Russia"
League.create :name => "Russia Cup", :url_param => "RussiaCup"
League.create :name => "Slovakia", :url_param => "Slovakia"
League.create :name => "Slovenia", :url_param => "Slovenia"
League.create :name => "Sweden", :url_param => "SwedAll"
League.create :name => "SwedSup", :url_param => "SwedSup"
League.create :name => "Sweden Cup", :url_param => "SwedenCup"
League.create :name => "Swiss SL", :url_param => "SwissNLAa"
League.create :name => "Swiss CL", :url_param => "SwissNLBa"
League.create :name => "Turkey", :url_param => "Turkey"
League.create :name => "Ukraine", :url_param => "Ukraine"
